name: Update badges

on:
  schedule:
    # Runs at 4:25 PM UTC every day
    - cron: "25 16 * * *"
  workflow_dispatch: # This allows manual triggering
    # You can optionally provide inputs if needed
    inputs:
      manual_run:
        description: 'Trigger manual run'
        required: false

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CREDLY_USER: <username_credly>
